version: "3"
services: 
  node-app: 
    build: .
    ports:
      - "3030:3030"
    volumes: 
      - ./:/app 
      - /app/node_modules
    environment:
       - ./.env
    container_name: nest_mogo